"use client";

import { useEffect, useState } from "react";
import { adminApi, getErrorMessage } from "@/lib/adminApi";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";

type Job = {
  id: string;
  rule_id?: string;
  job_type?: string;
  status?: string;
  scheduled_at?: string;
  started_at?: string;
  finished_at?: string;
  error_message?: string;
  note?: string;
};

const formatUtcToLocal = (value?: string) => {
  if (!value) return "—";

  const hasTimezone =
    /[zZ]$/.test(value) || // already UTC / with Z
    /[+-]\d{2}:\d{2}$/.test(value); // already has offset

  const normalized = hasTimezone
    ? value
    : `${value.replace(" ", "T")}Z`;

  const date = new Date(normalized);
  if (Number.isNaN(date.getTime())) return value;

  return date.toLocaleString();
};

export default function AdminAutomationJobsPage() {
  const [jobs, setJobs] = useState<Job[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [stoppingId, setStoppingId] = useState<string | null>(null);
  const [viewJob, setViewJob] = useState<Job | null>(null);

  const handleForceStop = async (jobId: string) => {
    if (!window.confirm("Force stop this job? It will be marked as cancelled.")) return;
    setStoppingId(jobId);
    setError(null);
    try {
      await adminApi.post(`/admin/automation/jobs/${jobId}/stop`);
      await loadJobs();
    } catch (err: unknown) {
      setError(getErrorMessage(err) || "Failed to stop job");
    } finally {
      setStoppingId(null);
    }
  };

  const loadJobs = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await adminApi.get<{ jobs: Job[] }>(
        "/admin/automation/jobs",
      );
      setJobs(res.data.jobs ?? []);
    } catch (err: unknown) {
      setError(getErrorMessage(err) || "Failed to load jobs");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadJobs();
  }, []);

  const hasErrorOrNote = (job: Job) =>
    (job.error_message && job.error_message.trim()) ||
    (job.note && job.note.trim());

  const errorOrNote = (job: Job) => job.error_message ?? job.note ?? "—";

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h1 className="text-lg font-semibold text-zinc-900">Automation Jobs</h1>
        <button
          onClick={loadJobs}
          className="rounded border px-3 py-1 text-xs font-medium hover:bg-zinc-100"
        >
          Refresh
        </button>
      </div>
      <p className="text-xs text-zinc-600">
        Executions generated by automation rules and other system tasks.
      </p>
      {error && <p className="text-xs text-red-600">{error}</p>}
      <div className="overflow-x-auto rounded border bg-white">
        <table className="min-w-full border-collapse text-xs">
          <thead className="bg-zinc-50">
            <tr>
              <th className="border-b px-2 py-2 text-left font-medium text-zinc-700">
                Job ID
              </th>
              <th className="border-b px-2 py-2 text-left font-medium text-zinc-700">
                Rule ID
              </th>
              <th className="border-b px-2 py-2 text-left font-medium text-zinc-700">
                Type
              </th>
              <th className="border-b px-2 py-2 text-left font-medium text-zinc-700">
                Status
              </th>
              <th className="border-b px-2 py-2 text-left font-medium text-zinc-700">
                Scheduled
              </th>
              <th className="border-b px-2 py-2 text-left font-medium text-zinc-700">
                Started
              </th>
              <th className="border-b px-2 py-2 text-left font-medium text-zinc-700">
                Finished
              </th>
              <th className="border-b px-2 py-2 text-left font-medium text-zinc-700">
                Error / Note
              </th>
              <th className="border-b px-2 py-2 text-right font-medium text-zinc-700">
                Actions
              </th>
            </tr>
          </thead>
          <tbody>
            {jobs.length === 0 && !loading && (
              <tr>
                <td
                  colSpan={9}
                  className="px-2 py-4 text-center text-xs text-zinc-500"
                >
                  No jobs found.
                </td>
              </tr>
            )}
            {jobs.map((job) => (
              <tr key={job.id} className="hover:bg-zinc-50">
                <td className="border-b px-2 py-2 font-mono text-[11px]">
                  {job.id}
                </td>
                <td className="border-b px-2 py-2 font-mono text-[11px]">
                  {job.rule_id ?? "—"}
                </td>
                <td className="border-b px-2 py-2 text-[11px]">
                  {job.job_type ?? "—"}
                </td>
                <td className="border-b px-2 py-2">
                  <span className="rounded bg-zinc-100 px-2 py-0.5 text-[11px] uppercase tracking-wide text-zinc-700">
                    {job.status ?? "pending"}
                  </span>
                </td>
                <td className="border-b px-2 py-2 text-[11px] text-zinc-500">
                  {formatUtcToLocal(job.scheduled_at)}
                </td>
                <td className="border-b px-2 py-2 text-[11px] text-zinc-500">
                  {formatUtcToLocal(job.started_at)}
                </td>
                <td className="border-b px-2 py-2 text-[11px] text-zinc-500">
                  {formatUtcToLocal(job.finished_at)}
                </td>
                <td className="border-b px-2 py-2 text-[11px] max-w-[220px]">
                  <div className="flex items-center gap-1">
                    <span className="truncate text-zinc-600">
                      {errorOrNote(job)}
                    </span>
                    {hasErrorOrNote(job) && (
                      <button
                        type="button"
                        onClick={() => setViewJob(job)}
                        className="shrink-0 rounded border border-zinc-300 px-1.5 py-0.5 text-[10px] font-medium text-zinc-600 hover:bg-zinc-100"
                      >
                        View full
                      </button>
                    )}
                  </div>
                </td>
                <td className="border-b px-2 py-2 text-right">
                  <div className="flex justify-end gap-1">
                    {hasErrorOrNote(job) && (
                      <button
                        type="button"
                        onClick={() => setViewJob(job)}
                        className="rounded border border-zinc-300 px-2 py-1 text-[11px] font-medium text-zinc-600 hover:bg-zinc-100"
                      >
                        View details
                      </button>
                    )}
                    {(job.status === "pending" || job.status === "running") && (
                      <button
                        type="button"
                        onClick={() => handleForceStop(job.id)}
                        disabled={stoppingId === job.id}
                        className="rounded border border-red-200 bg-red-50 px-2 py-1 text-[11px] font-medium text-red-700 hover:bg-red-100 disabled:opacity-50"
                      >
                        {stoppingId === job.id ? "Stopping…" : "Force Stop"}
                      </button>
                    )}
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      {loading && <p className="text-xs text-zinc-500">Loading jobs...</p>}

      <Dialog open={!!viewJob} onOpenChange={(open) => !open && setViewJob(null)}>
        <DialogContent className="max-h-[80vh] max-w-2xl overflow-y-auto">
          <DialogHeader>
            <DialogTitle>
              Job details{viewJob ? ` — ${viewJob.id.slice(0, 8)}...` : ""}
            </DialogTitle>
          </DialogHeader>
          {viewJob && (
            <div className="space-y-4">
              <div>
                <h4 className="mb-1 text-sm font-medium text-zinc-700">Error / Note</h4>
                <pre className="max-h-48 overflow-auto rounded border border-zinc-200 bg-zinc-50 p-3 text-xs text-zinc-800 whitespace-pre-wrap break-words">
                  {viewJob.error_message || viewJob.note || "(none)"}
                </pre>
              </div>
              <div className="flex justify-end">
                <button
                  type="button"
                  onClick={() => {
                    const text = viewJob.error_message ?? viewJob.note ?? "(none)";
                    void navigator.clipboard.writeText(text);
                  }}
                  className="rounded border border-zinc-300 px-3 py-1.5 text-xs font-medium text-zinc-600 hover:bg-zinc-100"
                >
                  Copy to clipboard
                </button>
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
}
